=== frantzoe/Webice/web/WEB-INF/database/recruiters.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="recruiters">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recruiter" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="forename" type="xs:string" />
                            <xs:element name="surname" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== frantzoe/Webice/web/WEB-INF/database/recruiters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<recruiters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recruiters.xsd">
    <recruiter>
        <forename>Emmanuel</forename>
        <surname>Doulin</surname>
        <email>e.doulin@mail.com</email>
        <password>5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8</password>
    </recruiter>
    <recruiter>
        <forename>Laborde</forename>
        <surname>Sophie</surname>
        <email>s.laborde@mail.com</email>
        <password>c0e21a8ff85153deac82fe7f09c0da1b3bd90ac0ae204e78d7148753b4363c03</password>
    </recruiter>
</recruiters>
